[meta]
name = "Grinding Stats"
author = "Drek"
category = "Overlay"
version = "3.0.0"
siteid = 158
module = "GrindingStats"

[script]
optional_dependencies = ["NadeoServices", "ChampionMedals", "DuckMedals"]
timeout = 5000
