[meta]
name = "Grinding Stats"
author = "Drek"
category = "Overlay"
version = "2.0.14"
siteid = 158
module = "GrindingStats"

[script]
optional_dependencies = [
    "NadeoServices",
    "ChampionMedals",
    "DuckMedals",
]
timeout = 5000
