[meta]
name = "Grinding Stats"
author = "Drek"
category = "Overlay"
version = "2.1.0"
siteid = 158
module = "GrindingStats"

[script]
optional_dependencies = ["NadeoServices","ChampionMedals","DuckMedals","WarriorMedals"]
timeout = 5000
