name: Release
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'grinding stats.zip'
          exclusions: '*.git* README.md'
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'grinding stats.zip'
          token: ${{ secrets.GITHUB_TOKEN }}